### ISSUE TITLE
Grayscale Implementation

### ISSUE THREAD

**Issue by orhuff** [menon92/WaveletCNN#1]
Could you please create an implementation of this code that would work with grayscale/1-channel images?

**Comment by menon92** [comment]
@orhuff, Please check [this](https://github.com/menon92/WaveletCNN/blob/master/waveletCNN_Keras_0_6_%5BExp_on_10K_data%5D_grayscale.ipynb) one - Thanks

**Comment by orhuff** [comment]
Thank you much appreciated!
